[package]
name = "sia_core"
version = "0.1.0"
edition = "2021"

[lib]
name = "sia_core"
path = "src/lib.rs"

[dependencies]
bip39 = "2.0.0"
blake2b_simd = "1.0.2"
ed25519-dalek = "2.1.1"
hex = "0.4.3"
serde = { version = "1.0.197", features = ["derive"] }
thiserror = "1.0.58"
