[workspace]
resolver = "2"
members = ["sia_core", "sia_core_derive", "sia_storage", "sia_storage_cabi", "sia_storage_ffi", "sia_storage_napi", "sia_storage_wasm", "sia_mux"]

# CPU-intensive operations (erasure coding, hashing, encryption) are
# ~100x slower without optimizations. Some tests will be extremely
# slow without this.
[profile.dev]
opt-level = 3

[profile.release]
lto = "thin"
codegen-units = 1
