[changes]
ignore_conventional_commits = true

[packages.sia_core]
versioned_files = [
    "sia_core/Cargo.toml",
    { path = "sia_storage/Cargo.toml", dependency = "sia_core" },
    { path = "sia_storage_ffi/Cargo.toml", dependency = "sia_core" },
    { path = "sia_storage_napi/Cargo.toml", dependency = "sia_core" },
    { path = "sia_storage_wasm/Cargo.toml", dependency = "sia_core" },
    { path = "Cargo.lock", dependency = "sia_core" }
]
changelog = "sia_core/CHANGELOG.md"

[packages.sia_core_derive]
versioned_files = [
    "sia_core_derive/Cargo.toml",
    { path = "sia_core/Cargo.toml", dependency = "sia_core_derive" },
    { path = "sia_storage/Cargo.toml", dependency = "sia_core_derive" },
    { path = "Cargo.lock", dependency = "sia_core_derive" }
]
changelog = "sia_core_derive/CHANGELOG.md"

[packages.sia_storage]
versioned_files = [
    "sia_storage/Cargo.toml",
    { path = "sia_storage_ffi/Cargo.toml", dependency = "sia_storage" },
    { path = "sia_storage_napi/Cargo.toml", dependency = "sia_storage" },
    { path = "sia_storage_wasm/Cargo.toml", dependency = "sia_storage" },
    { path = "Cargo.lock", dependency = "sia_storage" }
]
changelog = "sia_storage/CHANGELOG.md"

[packages.sia_storage_ffi]
versioned_files = [
    "sia_storage_ffi/Cargo.toml",
    { path = "Cargo.lock", dependency = "sia_storage_ffi" }
]
changelog = "sia_storage_ffi/CHANGELOG.md"

[packages.sia_storage_napi]
versioned_files = [
    "sia_storage_napi/Cargo.toml",
    { path = "Cargo.lock", dependency = "sia_storage_napi" }
]
changelog = "sia_storage_napi/CHANGELOG.md"

[packages.sia_storage_wasm]
versioned_files = [
    "sia_storage_wasm/Cargo.toml",
    { path = "Cargo.lock", dependency = "sia_storage_wasm" }
]
changelog = "sia_storage_wasm/CHANGELOG.md"

[packages.sia_storage_cabi]
versioned_files = [
    "sia_storage_cabi/Cargo.toml",
    { path = "Cargo.lock", dependency = "sia_storage_cabi" }
]
changelog = "sia_storage_cabi/CHANGELOG.md"

[packages.sia_mux]
versioned_files = [
    "sia_mux/Cargo.toml",
    { path = "sia_storage/Cargo.toml", dependency = "sia_mux" },
    { path = "Cargo.lock", dependency = "sia_mux" }
]
changelog = "sia_mux/CHANGELOG.md"

[[workflows]]
name = "document-change"

[[workflows.steps]]
type = "CreateChangeFile"

[[workflows]]
name = "prepare-release"

[[workflows.steps]]
type = "PrepareRelease"

[[workflows]]
name = "release"

[[workflows.steps]]
type = "Release"

[github]
owner = "SiaFoundation"
repo = "sia-sdk-rs"
