[packages.sia_sdk]
versioned_files = ["sia/Cargo.toml"]
changelog = "sia/CHANGELOG.md"

[packages.sia_sdk_derive]
versioned_files = ["sia_derive/Cargo.toml"]
changelog = "sia_derive/CHANGELOG.md"

[[workflows]]
name = "prepare-release"

[[workflows.steps]]
type = "PrepareRelease"

[[workflows]]
name = "release"

[[workflows.steps]]
type = "Release"

[github]
owner = "SiaFoundation"
repo = "sia-sdk-rs"
