[package]
name = "sia_storage_napi"
version = "0.10.0"
edition = "2024"
repository = "https://github.com/SiaFoundation/sia-sdk-rs"
license = "MIT"
description = "Node.js N-API bindings for interacting with a Sia network indexer"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
bytes = "1.12.1"
futures-core = "0.3.33"
log = "0.4.33"
chrono = { version = "0.4", features = ["serde"] }
napi = { version = "3.11.0", features = ["async", "napi8", "chrono_date", "web_stream"] }
napi-derive = { version = "3.6.0", features = ["type-def"] }
sia_core = { version = "0.5.0", path = "../sia_core" }
sia_storage = { version = "0.12.0", path = "../sia_storage", features = ["fs"] }
thiserror = "2.0.19"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "sync"] }
tokio-stream = "0.1"
tokio-util = { version = "0.7", features = ["io"] }

[build-dependencies]
napi-build = "2"
