name: Prepare Release

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  prepare-release:
    if: "!contains(github.event.head_commit.message, 'chore: prepare releases')" # Skip merges from releases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Environment
        run: |
          rustup update stable
          cargo install knope
      - name: Prepare Release
        run: knope prepare-release --verbose
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          delete-branch: true
          commit-message: "chore: prepare releases"
          title: Release Versions
          base: master
          branch: release
          body: |
            This PR was automatically created to prepare the release versions. Close the PR when you are ready to release. See the changelog for more details.
