name: Release

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  release:
    if: github.head_ref == 'release' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Environment
        run: |
          rustup update stable
          cargo install knope
      - name: Release
        run: |
          knope release
          cargo publish -p sia_sdk_derive
          cargo publish -p sia_sdk
